### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by cup** [blogc/blogc#13]
thank you

**Comment by rafaelmartins** [comment]
Our "input language" is based on John Gruber's Markdown, then most of its syntax should work, but we don't aim at full compliance with the spec, neither support "extensions" like github-flavoured-markdown or common-mark. However, if some non-implemented feature is important for you, feel free to open another bugs requesting them, and they will be considered.

**Comment by cup** [comment]
@rafaelmartins is another repo available for the markup implementation? it seems odd to post spec changes to the generator repo

**Comment by rafaelmartins** [comment]
The implementation and spec are all in this repo.

spec: https://github.com/blogc/blogc/blob/master/man/blogc-source.7.ronn (rendered here: https://blogc.rgm.io/man/blogc-source.7.html )
implementation: https://github.com/blogc/blogc/blob/master/src/blogc/content-parser.c
