### ISSUE TITLE
additional templates ready-made to use

### ISSUE THREAD

**Issue by DingoDog** [blogc/blogc#2]
Hi

I recently discovered blogc

I ended up to compile successfully in Puppy slacko 5.3.1 after some minor tweaks to source code 

I want to ask if the template  and the css used to build your example site

https://blogc.rgm.io/

(now unreachable, apart the cache in google)

are available and how to use to change the default css and template used by blogc

thanks in advance

**Comment by rafaelmartins** [comment]
Hi,

could you please share your source code tweaks? preferably as a patch or pull request? :)

the website looks ok for me, if it still fail for you, please do some network testing (curl, mtr, etc) and send me the logs in private.

the website is based on the example repository (https://github.com/blogc/blogc-example), feel free to use it as base for your own website. Some outdated sources of blogc.rgm.io are also available here: https://github.com/blogc/blogc.org

**Comment by DingoDog** [comment]
Thanks for reply, I suspect the tweaks I made to some files of source code are only needed  for puppy linux series (slacko 5.3.1); I remember I added

--------------------------
m4_pattern_allow

AM_PROG_CC_C_O
----------------------------
to configure.ac

removing 

AM_PROG_AR

due to problems I encountered with autoconf 2.69

but, as said, I really think this is an issue only for puppy linux and you can ignore these tweaks in your development (thanks for developing blogc for instance), especially once I found the corrections to compile successfully in puppy. I think I'll made a patch only for puppy linux in puppy linux repositories and forum spreading blogc

a really useful tiny static generator without bloating dependencies

regarding the site https://blogc.rgm.io/, I'm able to reach trough a proxy or some vpn foreign based - some countries ok, some ko - (I suspect the .io domains are blocked at IP address level in my country, infamous for censorship)

I'll try to build my blog looking exactly like https://blogc.rgm.io/, I like its css and template

**Comment by rafaelmartins** [comment]
Hi,

you may want to use official releases to install blogc, instead of cloning git repository. most of your autotools issues won't exist if you use a tarball from https://github.com/blogc/blogc/releases, like:

https://github.com/blogc/blogc/releases/download/v0.5.1/blogc-0.5.1.tar.gz

about your issues accessing the site, it seems that you have a firewall blocking it. I don't know if I can do something to fix it.

thanks
