### ISSUE TITLE
HTML/XML inside code blocks should be parsed

### ISSUE THREAD

**Issue by shiba89** [blogc/blogc#3]
Right now the only way to show HTML/XML code in a code block is to manually escape it with ampersands in the source code of pages/posts. Here are two images to explain the problem (source on the left, rendering on the right):

Wrong rendering
![blogc_wrong](https://cloud.githubusercontent.com/assets/3816409/12477664/17bb6af8-c031-11e5-8fb6-4f021b92b594.png)

Correct rendering
![blogc_right](https://cloud.githubusercontent.com/assets/3816409/12477690/38913e38-c031-11e5-9522-bea2c815d560.png)

**Comment by rafaelmartins** [comment]
Yeah, you are correct. This is a "known" issue. i work around it with CDATA in atom feeds, but I know that this isn't applicable in all the cases:

https://github.com/blogc/blogc-example/blob/master/templates/atom.tmpl#L24

I'll see what can I do to fix it tonight.

Thanks

**Comment by shiba89** [comment]
Works like a charm (sorry I could test it only today), thank you :D
